from . import mademan_barber
from . import mademan_customer
from . import mademan_service
from . import mademan_appointment
from . import mademan_dashboard
from . import mademan_visit
from . import mademan_charge
from . import mademan_payment
from . import mademan_visit_completion
from . import mademan_homepage